Fix build scripts: add dh-dkms dependency
The .deb package build was failing on CM5 with:
  error: unable to load addon dkms: Can't locate Debian/Debhelper/Sequence/dkms.pm

This is because dh-dkms package was missing, which provides the DKMS
integration for debhelper.

Fixed in:
- build-on-pi.sh: Added dh-dkms to installation list
- create-apt-repo.sh: Added dh-dkms to installation list

Now building on CM5 and other Debian systems will work correctly.